/** Política de privacidad — texto base: FitEngine_Politica_Privacidad.docx (abr. 2026). Responsable: Rodrigo Pérez Pulti. */
const paragraphs = [
  'Responsable: Rodrigo Pérez Pulti (DNI 28.519.402) — operando bajo la marca FitEngine by WAITOMO',
  '',
  'Contacto: soporte@waitomo.com',
  '',
  'Domicilio: Maipú, Provincia de Buenos Aires, Argentina',
  '',
  '—',
  '',
  '1. Introducción',
  '',
  'Esta Política de Privacidad describe cómo FitEngine by WAITOMO ("nosotros", "la plataforma") recopila, usa, almacena y protege la información personal de las personas que usan la aplicación FitEngine ("la App") y los servicios relacionados. Al crear una cuenta o usar la App, aceptás esta política.',
  '',
  '2. Quién es responsable de tus datos',
  '',
  'El responsable del tratamiento de datos es Rodrigo Pérez Pulti (DNI 28.519.402), con domicilio en Maipú, Provincia de Buenos Aires, Argentina, contactable en soporte@waitomo.com. FitEngine es la plataforma tecnológica; cada organización (gimnasio, coach) que la utiliza es co-responsable de los datos de sus propios clientes dentro de su espacio.',
  '',
  '3. Qué datos recopilamos',
  '',
  '3.1 Datos que vos proporcionás',
  '',
  '• Nombre y apellido\n• Dirección de correo electrónico\n• Foto de perfil (opcional)\n• Información de salud general vinculada a tus planes de entrenamiento (opcional)\n• Mensajes enviados dentro de la App',
  '',
  '3.2 Datos generados por el uso',
  '',
  '• Registro de asistencia a clases y reservas\n• Progreso en planes y rutinas de entrenamiento\n• Estado de abono o membresía (informado por tu organización)\n• Preferencias de configuración de la App (tema, idioma, notificaciones)',
  '',
  '3.3 Datos técnicos',
  '',
  '• Identificador de dispositivo y versión del sistema operativo\n• Registros de errores y uso (para mejora del servicio)',
  '',
  'No recopilamos datos de pago directamente. Los pagos son gestionados por la organización a la que pertenecés, fuera de la App.',
  '',
  '4. Para qué usamos tus datos',
  '',
  '• Brindarte acceso a los servicios contratados (planes, clases, rutinas, mensajes)\n• Permitir que tu coach o el staff del gimnasio gestione tu progreso y membresía\n• Enviarte notificaciones relacionadas con tu entrenamiento o plan\n• Mejorar el funcionamiento de la plataforma\n• Cumplir con obligaciones legales',
  '',
  'No usamos tus datos para publicidad de terceros ni los vendemos bajo ninguna circunstancia.',
  '',
  '5. Con quién compartimos tus datos',
  '',
  'Compartimos datos solo en los siguientes casos:',
  '',
  '• Con el staff autorizado de tu organización (coach, administrador), para gestionar tu entrenamiento y membresía.\n• Con Supabase (proveedor de base de datos e infraestructura en la nube), que actúa como encargado del tratamiento. Supabase cumple con estándares internacionales de seguridad (SOC 2 Type II, ISO 27001).\n• Con Expo (plataforma de distribución de la App), para actualizaciones y funcionamiento técnico.\n• Con autoridades competentes, si existiera obligación legal de hacerlo.',
  '',
  'Todos nuestros proveedores operan bajo acuerdos de confidencialidad y con estándares adecuados de protección de datos.',
  '',
  '6. Transferencias internacionales',
  '',
  'La infraestructura de Supabase puede almacenar datos en servidores ubicados en Estados Unidos u otras jurisdicciones. Estos proveedores cuentan con mecanismos de adecuación reconocidos internacionalmente. Si tenés consultas sobre la ubicación de tus datos, contactanos en soporte@waitomo.com.',
  '',
  '7. Por cuánto tiempo guardamos tus datos',
  '',
  'Conservamos tus datos mientras tu cuenta esté activa o mientras la organización a la que pertenecés esté operativa en la plataforma. Si solicitás la eliminación de tu cuenta, eliminaremos tu información personal en un plazo de 30 días, salvo que exista obligación legal de conservarla.',
  '',
  '8. Seguridad',
  '',
  'Implementamos medidas técnicas y organizativas para proteger tu información: conexiones cifradas (TLS/HTTPS), autenticación segura, control de acceso por roles y políticas de seguridad a nivel de fila (Row Level Security) en la base de datos. Ningún sistema es 100% infalible; en caso de brecha de seguridad que afecte tus datos, te notificaremos en el plazo establecido por la legislación aplicable.',
  '',
  '9. Tus derechos',
  '',
  'De acuerdo con la Ley Nacional 25.326 de Protección de Datos Personales (Argentina) y principios del RGPD/GDPR para usuarios del exterior, tenés derecho a:',
  '',
  '• Acceder a los datos personales que tenemos sobre vos\n• Rectificar datos incorrectos o desactualizados\n• Solicitar la eliminación de tus datos ("derecho al olvido")\n• Oponerte al tratamiento de tus datos en ciertos supuestos\n• Solicitar la portabilidad de tus datos',
  '',
  'Para ejercer estos derechos, escribinos a soporte@waitomo.com. Responderemos dentro de los 30 días. La Dirección Nacional de Protección de Datos Personales (DNPDP) de Argentina es la autoridad de control competente.',
  '',
  '10. Menores de edad',
  '',
  'La App no está destinada a menores de 16 años sin supervisión de un adulto responsable. No recopilamos conscientemente datos de menores sin autorización parental. Si detectás que un menor ha creado una cuenta, contactanos para eliminación inmediata.',
  '',
  '11. Cookies y tecnologías similares',
  '',
  'La App móvil no utiliza cookies. Podemos usar almacenamiento local del dispositivo para guardar preferencias de usuario (tema, idioma) de forma no vinculante a identidades externas.',
  '',
  '12. Cambios a esta política',
  '',
  'Podemos actualizar esta Política de Privacidad. Te notificaremos a través de la App o por email ante cambios significativos. La versión vigente siempre estará disponible dentro de la App en Configuración → Acerca de → Política de privacidad.',
  '',
  '13. Contacto',
  '',
  'Para cualquier consulta sobre privacidad: soporte@waitomo.com',
  '',
  'Domicilio de contacto: Maipú, Provincia de Buenos Aires, Argentina',
];

export default paragraphs.join('\n\n');
