/** Terms of use — English version aligned with FitEngine_Terminos_Condiciones (Apr 2026). */
const paragraphs = [
  'Responsible party: Rodrigo Pérez Pulti (National ID 28,519,402) — operating under the brand FitEngine by WAITOMO',
  '',
  'Contact: soporte@fitengine.app',
  '',
  'Address: Maipú, Buenos Aires Province, Argentina',
  '',
  '—',
  '',
  '1. Acceptance',
  '',
  'By downloading, installing, or using the FitEngine application (“the App”), you accept these Terms and Conditions (“Terms”) in full. If you do not agree, do not use the App. These Terms constitute a legally binding agreement between you (“user”) and Rodrigo Pérez Pulti, operator of FitEngine by WAITOMO.',
  '',
  '2. Description of the service',
  '',
  'FitEngine is a multi-tenant SaaS platform that allows gyms and coaches to manage memberships, training plans, classes, bookings, and communication with their clients. The service is provided through the mobile App available on Google Play and the Apple App Store.',
  '',
  'There are two main types of users:',
  '',
  '• Clients: users who access services from their gym or coach through the App.\n• Organizations (gyms and coaches): entities that use FitEngine to run operations and offer services to their clients.',
  '',
  '3. Registration and account',
  '',
  '• To use the App you must create an account with truthful, up-to-date information.\n• You are responsible for keeping your password confidential.\n• You may not transfer your account to third parties.\n• Your access is tied to the organization (gym/coach) you belong to. If your membership ends or your organization stops operating on the platform, your access may be limited.\n• A single email address may be linked to only one organization at a time.',
  '',
  '4. Acceptable use',
  '',
  'You use the App lawfully and in good faith. The following is prohibited:',
  '',
  '• Impersonating another user, coach, or administrator\n• Using the App for fraudulent, illegal, or harmful activities\n• Attempting to access other organizations’ or users’ data without authorization\n• Reverse engineering, decompiling, or modifying the App\n• Using bots, scripts, or other automated tools to interact with the App\n• Uploading offensive, discriminatory, violent content or content that infringes third-party rights',
  '',
  '5. Plans, subscriptions, and payments',
  '',
  'Feature availability in the App depends on the plan contracted by your organization and your membership or subscription status.',
  '',
  '• Membership payments are handled directly by your gym or coach, outside the App (unless stated otherwise).\n• FitEngine does not process payments directly and is not responsible for billing disputes between users and organizations.\n• Organizations that contract FitEngine accept the commercial terms agreed separately with the platform operator.',
  '',
  '6. Content and intellectual property',
  '',
  '6.1 Platform content',
  '',
  'The FitEngine name, logo, App design, and all related software are the property of Rodrigo Pérez Pulti / WAITOMO. Reproduction or use without express authorization is prohibited.',
  '',
  '6.2 Organization content',
  '',
  'Routines, plans, videos, and training materials uploaded by gyms and coaches belong to those organizations. FitEngine only acts as a storage and distribution platform.',
  '',
  '6.3 Your content',
  '',
  'By uploading profile photos or other content, you grant FitEngine a limited license to display it within the App in the context of your account.',
  '',
  '7. Liability and health',
  '',
  'FitEngine is a training management and tracking tool. We are not responsible for:',
  '',
  '• Injuries, physical harm, or health consequences from using plans or routines available in the App\n• The quality, accuracy, or suitability of training plans uploaded by organizations\n• Medical or health decisions based on App content',
  '',
  'App content does not replace professional medical advice. Consult a health professional before starting any exercise program.',
  '',
  '8. Service availability',
  '',
  'We do our best to keep the App available. However, we do not guarantee uninterrupted availability. We may perform scheduled or corrective maintenance that causes temporary interruptions, with or without prior notice depending on urgency.',
  '',
  '9. Limitation of liability',
  '',
  'To the fullest extent permitted by law, Rodrigo Pérez Pulti and FitEngine by WAITOMO shall not be liable for indirect, incidental, special, or consequential damages arising from use or inability to use the App. Total maximum liability to a user shall not exceed the amount paid (if any) for use of the service in the 12 months prior to the claim.',
  '',
  '10. Changes to the service and these Terms',
  '',
  'We reserve the right to modify, suspend, or discontinue any App feature at any time. We may also update these Terms; we will notify you in the App. Continued use after notification constitutes acceptance of the new Terms.',
  '',
  '11. Termination',
  '',
  'We may suspend or delete your account if you violate these Terms, without prior notice in serious cases. You may request account deletion at any time by writing to soporte@fitengine.app.',
  '',
  '12. Governing law and jurisdiction',
  '',
  'These Terms are governed by the laws of the Argentine Republic. For any dispute, the parties submit to the ordinary courts of Buenos Aires Province, seated in Maipú, waiving any other jurisdiction that may apply.',
  '',
  '13. Contact',
  '',
  'For questions about these Terms: soporte@fitengine.app',
  '',
  'Address: Maipú, Buenos Aires Province, Argentina',
];

export default paragraphs.join('\n\n');
