/** Términos y condiciones — texto base: FitEngine_Terminos_Condiciones.docx (abr. 2026). Responsable: Rodrigo Pérez Pulti. */
const paragraphs = [
  'Responsable: Rodrigo Pérez Pulti (DNI 28.519.402) — operando bajo la marca FitEngine by WAITOMO',
  '',
  'Contacto: soporte@waitomo.com',
  '',
  'Domicilio: Maipú, Provincia de Buenos Aires, Argentina',
  '',
  '—',
  '',
  '1. Aceptación',
  '',
  'Al descargar, instalar o usar la aplicación FitEngine ("la App"), aceptás estos Términos y Condiciones ("Términos") en su totalidad. Si no estás de acuerdo, no uses la App. Estos Términos constituyen un acuerdo legalmente vinculante entre vos ("usuario") y Rodrigo Pérez Pulti, operador de FitEngine by WAITOMO.',
  '',
  '2. Descripción del servicio',
  '',
  'FitEngine es una plataforma SaaS multi-tenant que permite a gimnasios y coaches gestionar membresías, planes de entrenamiento, clases, reservas y comunicación con sus clientes. El servicio se presta a través de la App móvil disponible en Google Play Store y Apple App Store.',
  '',
  'Existen dos tipos de usuarios principales:',
  '',
  '• Clientes: usuarios que acceden a los servicios de su gimnasio o coach a través de la App.\n• Organizaciones (gyms y coaches): entidades que contratan FitEngine para gestionar sus operaciones y ofrecer servicios a sus clientes.',
  '',
  '3. Registro y cuenta',
  '',
  '• Para usar la App debés crear una cuenta con información verdadera y actualizada.\n• Sos responsable de mantener la confidencialidad de tu contraseña.\n• No podés ceder tu cuenta a terceros.\n• Tu acceso está vinculado a la organización (gimnasio/coach) a la que pertenecés. Si tu membresía vence o tu organización deja de operar en la plataforma, tu acceso puede verse limitado.\n• Una misma dirección de email puede estar asociada a una sola organización a la vez.',
  '',
  '4. Uso aceptable',
  '',
  'Usás la App de manera lícita y de buena fe. Está prohibido:',
  '',
  '• Suplantar la identidad de otro usuario, coach o administrador\n• Usar la App para actividades fraudulentas, ilegales o que dañen a otros usuarios\n• Intentar acceder a datos de otras organizaciones o usuarios sin autorización\n• Realizar ingeniería inversa, descompilar o modificar la App\n• Usar bots, scripts u otras herramientas automatizadas para interactuar con la App\n• Cargar contenido ofensivo, discriminatorio, violento o que viole derechos de terceros',
  '',
  '5. Planes, abonos y pagos',
  '',
  'La disponibilidad de funciones dentro de la App depende del plan contratado por tu organización y del estado de tu membresía o abono.',
  '',
  '• Los pagos de membresías son gestionados directamente por tu gimnasio o coach, fuera de la App (salvo que se indique lo contrario).\n• FitEngine no procesa pagos directamente y no es responsable por disputas de cobro entre usuarios y organizaciones.\n• Las organizaciones que contratan FitEngine aceptan los términos comerciales acordados por separado con el operador de la plataforma.',
  '',
  '6. Contenido y propiedad intelectual',
  '',
  '6.1 Contenido de la plataforma',
  '',
  'El nombre FitEngine, el logo, el diseño de la App y todo el software asociado son propiedad de Rodrigo Pérez Pulti / WAITOMO. Queda prohibida su reproducción o uso sin autorización expresa.',
  '',
  '6.2 Contenido de las organizaciones',
  '',
  'Rutinas, planes, videos y materiales de entrenamiento subidos por gimnasios y coaches son propiedad de dichas organizaciones. FitEngine solo actúa como plataforma de almacenamiento y distribución.',
  '',
  '6.3 Tu contenido',
  '',
  'Al cargar fotos de perfil u otro contenido, otorgás a FitEngine una licencia limitada para mostrarlo dentro de la App en el contexto de tu cuenta.',
  '',
  '7. Responsabilidad y salud',
  '',
  'FitEngine es una herramienta de gestión y seguimiento de entrenamiento. No somos responsables por:',
  '',
  '• Lesiones, daños físicos o consecuencias para la salud derivadas del uso de los planes o rutinas disponibles en la App\n• La calidad, precisión o adecuación de los planes de entrenamiento cargados por las organizaciones\n• Decisiones médicas o de salud tomadas en base al contenido de la App',
  '',
  'El contenido de la App no reemplaza el asesoramiento médico profesional. Consultá a un profesional de la salud antes de iniciar cualquier programa de ejercicios.',
  '',
  '8. Disponibilidad del servicio',
  '',
  'Hacemos nuestro mejor esfuerzo para mantener la App disponible. Sin embargo, no garantizamos disponibilidad ininterrumpida. Podemos realizar mantenimientos programados o correctivos que impliquen interrupciones temporales, con o sin aviso previo según la urgencia.',
  '',
  '9. Limitación de responsabilidad',
  '',
  'En la máxima medida permitida por la ley, Rodrigo Pérez Pulti y FitEngine by WAITOMO no serán responsables por daños indirectos, incidentales, especiales o consecuentes derivados del uso o imposibilidad de uso de la App. La responsabilidad total máxima frente a un usuario no excederá el monto pagado (si hubiera) por el uso del servicio en los 12 meses previos al reclamo.',
  '',
  '10. Modificaciones al servicio y a estos Términos',
  '',
  'Nos reservamos el derecho de modificar, suspender o discontinuar cualquier función de la App en cualquier momento. También podemos actualizar estos Términos; te notificaremos dentro de la App. El uso continuado de la App tras la notificación implica aceptación de los nuevos Términos.',
  '',
  '11. Terminación',
  '',
  'Podemos suspender o eliminar tu cuenta si violás estos Términos, sin aviso previo en casos graves. Vos podés solicitar la eliminación de tu cuenta en cualquier momento escribiendo a soporte@waitomo.com.',
  '',
  '12. Ley aplicable y jurisdicción',
  '',
  'Estos Términos se rigen por las leyes de la República Argentina. Para cualquier controversia, las partes se someten a la jurisdicción de los tribunales ordinarios de la Provincia de Buenos Aires, con asiento en Maipú, renunciando a cualquier otro fuero que pudiera corresponder.',
  '',
  '13. Contacto',
  '',
  'Para consultas sobre estos Términos: soporte@waitomo.com',
  '',
  'Domicilio: Maipú, Provincia de Buenos Aires, Argentina',
];

export default paragraphs.join('\n\n');
